ALTER TABLE payments
ADD COLUMN IF NOT EXISTS membership_months INTEGER,
ADD COLUMN IF NOT EXISTS session_count INTEGER,
ADD COLUMN IF NOT EXISTS card_holder_name VARCHAR(120),
ADD COLUMN IF NOT EXISTS card_last4 VARCHAR(4);
