const replacements: Array<[string, string]> = [
  ["Admin Kullanici", "Admin Kullanıcı"],
  ["Admin Kullanıcı", "Yönetici Kullanıcı"],
  ["Mert Yildiz", "Mert Yıldız"],
  ["Strength & Conditioning Coach", "Kuvvet ve Kondisyon Koçu"],
  ["Pilates ve Mobility Uzmani", "Pilates ve Mobilite Uzmanı"],
  ["Pilates ve Mobility Uzmanı", "Pilates ve Mobilite Uzmanı"],
  ["Mobility Coach", "Mobilite Koçu"],
  ["Functional Training Coach", "Fonksiyonel Antrenman Koçu"],
  ["Personal Training Coach", "Kişisel Antrenman Koçu"],
  ["Morning Pilates", "Sabah Pilatesi"],
  ["HIIT Blast", "Yoğun HIIT Dersi"],
  ["Functional Burn", "Fonksiyonel Yakım Dersi"],
  ["Posture Reset", "Duruş Dengeleme Dersi"],
  ["Strong Legs", "Güçlü Bacak Dersi"],
  ["Strength", "Kuvvet"],
  ["Coach", "Koçu"],
  ["Core", "Merkez Bölge"],
  ["Mobility", "Mobilite"],
  ["Pilates", "Pilates"],
  ["Yoga", "Yoga"],
  ["Reformer", "Reformer"],
  ["Cross Training", "Çapraz Antrenman"],
  ["TRX Coach", "TRX Koçu"],
  ["TRX Training", "TRX Eğitimi"],
  ["Women Strength Specialist", "Kadın Güçlenme Uzmanı"],
  ["Cross Training Performance", "Çapraz Antrenman Performansı"],
  ["Reformer Advanced Coach", "İleri Seviye Reformer Koçu"],
  ["Balanced Body Pilates", "Dengeli Vücut Pilatesi"],
  ["Balanced Body", "Dengeli Vücut"],
  ["Performance", "Performans"],
  ["Specialist", "Uzmanı"],
  ["Advanced", "İleri Seviye"],
  ["World Greatest Stretch", "Gelişmiş Esneme Serisi"],
  ["Dead Bug", "Ters Kol Bacak Açışı"],
  ["Romanian Deadlift", "Romen Bel Çekişi"],
  ["Goblet Squat", "Goblet Çömelme"],
  ["Incline Push-Up", "Eğimli Şınav"],
  ["Hip Thrust", "Kalça İtişi"],
  ["Lat Pulldown", "Geniş Tutuş Çekiş"],
  ["Seated Row", "Oturarak Kürek Çekişi"],
  ["Walking Lunge", "Yürüyüş Lunge"],
  ["Plank Reach", "Plank Uzatma"],
  ["Upper Body", "Üst Vücut"],
  ["Lower Body", "Alt Vücut"],
  ["Full Body", "Tüm Vücut"],
  ["Studio A", "Stüdyo A"],
  ["Studio B", "Stüdyo B"],
  ["Gold", "Altın"],
  ["Silver", "Gümüş"],
  ["Starter", "Başlangıç"],
  ["Uyelikte %10 Indirim", "Üyelikte %10 İndirim"],
  ["Bir sonraki uyelik yenilemesinde indirim.", "Bir sonraki üyelik yenilemesinde indirim."],
  ["Protein Bar", "Protein Barı"],
  ["Misafir Girisi", "Misafir Girişi"],
  ["Kullan at havlu paketi", "Kullan at havlu paketi"],
  ["active", "Aktif"],
  ["draft", "Taslak"]
];

export function cevirMetin(text: string | null | undefined) {
  if (!text) return "";

  return replacements.reduce((current, [source, target]) => {
    return current.split(source).join(target);
  }, text);
}
